## Deliverable 3. Create a Travel Itinerary Map.

In [5]:
# Dependencies and Setup
import pandas as pd
import requests
import gmaps
import numpy as np

# Import API key
from config import g_key

# Configure gmaps
gmaps.configure(api_key=g_key)

In [6]:
# 1. Read the WeatherPy_vacation.csv into a DataFrame.
vacation_df = pd.read_csv("WeatherPy_Vacation.csv")
vacation_df

City ID      City Country  Max Temp    Lat     Lng  \
0         10    Vanimo      PG     85.87  -2.67  141.30   
1         12      Bals      RO     70.00  44.35   24.10   
2         14  Kirakira      SB     85.98 -10.45  161.92   
3         17    Atuona      PF     78.62  -9.80 -139.03   
4         18     Kapaa      US     86.00  22.08 -159.32   
..       ...       ...     ...       ...    ...     ...   
289      672   Aquiraz      BR     78.80  -3.90  -38.39   
290      675  Damietta      EG     82.40  31.42   31.81   
291      676     Kuryk      KZ     71.98  43.20   51.65   
292      677  Tomatlan      MX     76.26  19.93 -105.25   
293      680       Bud      US     70.00  39.45  -86.18   

                                            Hotel Name  
0                                Vahmoneh Lodge Vanimo  
1                           Avangarde Hotel Restaurant  
2                                         SanBiz Lodge  
3                                          Villa Enata  
4               Sheraton Kauai Resort at Coconut Beach  
..                                                 ...  
289                                   Hotel Laguna Blu  
290                             العواد لتجارة الابلكاش  
291  Gostinitsa Kuryk - Otel' Dlya Vsekh Kategoriy ...  
292                                       Norma franco  
293                                Madsion Scouts Camp  

[294 rows x 7 columns]

In [7]:
# 2. Using the template add the city name, the country code, the weather description and maximum temperature for the city.
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Max Temp</dt><dd>{Max Temp} °F</dd>
</dl>
"""

# 3a. Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in vacation_df.iterrows()]

# 3b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = vacation_df[["Lat", "Lng"]]

In [8]:
# 4a. Add a marker layer for each city to the map.
max_temp = vacation_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(marker_layer)

# 4b. Display the figure
fig


Figure(layout=FigureLayout(height='420px'))

In [9]:
# From the map above pick 4 cities and create a vacation itinerary route to travel between the four cities. 
# 5. Create DataFrames for each city by filtering the 'vacation_df' using the loc method. 
# Hint: The starting and ending city should be the same city.

vacation_start = vacation_df.loc[(vacation_df["City"] == "Tutoia")]
vacation_end = vacation_df.loc[(vacation_df["City"] == "Tutoia")]
vacation_stop1 = vacation_df.loc[(vacation_df["City"] == "Aquiraz")]
vacation_stop2 = vacation_df.loc[(vacation_df["City"] == "Touros")]
vacation_stop3 = vacation_df.loc[(vacation_df["City"] == "Pitimbu")]

In [10]:
# 6. Get the latitude-longitude pairs as tuples from each city DataFrame using the to_numpy function and list indexing.
start = np.round(vacation_start[["Lat", "Lng"]].to_numpy(),1)
end = np.round(vacation_end[["Lat", "Lng"]].to_numpy(),1)
stop1 = np.round(vacation_stop1[["Lat", "Lng"]].to_numpy(),1)
stop2 = np.round(vacation_stop2[["Lat", "Lng"]].to_numpy(),1)
stop3 = np.round(vacation_stop3[["Lat", "Lng"]].to_numpy(),1)

start,end,stop1,stop2,stop3


(array([[ -2.8, -42.3]]),
 array([[ -2.8, -42.3]]),
 array([[ -3.9, -38.4]]),
 array([[ -5.2, -35.5]]),
 array([[ -7.5, -34.8]]))

In [11]:
# 7. Create a direction layer map using the start and end latitude-longitude pairs,
# and stop1, stop2, and stop3 as the waypoints. The travel_mode should be "DRIVING", "BICYCLING", or "WALKING".

start_map = -2.8, -42.3
end_map = -2.8, -42.3
stop1_map = -3.9, -38.4
stop2_map = -5.2, -35.5
stop3_map = -7.5, -34.8

fig = gmaps.figure()
brazil_trip = gmaps.directions_layer(start_map, end_map, waypoints=[stop1_map, stop2_map, stop3_map], travel_mode="DRIVING")
fig.add_layer(brazil_trip)
fig

Figure(layout=FigureLayout(height='420px'))

In [12]:
# 8. To create a marker layer map between the four cities.
#  Combine the four city DataFrames into one DataFrame using the concat() function.
itinerary_df = pd.concat([vacation_start, vacation_stop1, vacation_stop2, vacation_stop3],ignore_index=True)
itinerary_df

City ID     City Country  Max Temp   Lat    Lng        Hotel Name
0      170   Tutoia      BR     80.44 -2.76 -42.27   Pousada Guará's
1      672  Aquiraz      BR     78.80 -3.90 -38.39  Hotel Laguna Blu
2      263   Touros      BR     75.20 -5.20 -35.46   INN NEW HORIZON
3       96  Pitimbu      BR     73.40 -7.47 -34.81  Reserva do Abiaí

In [13]:
# 9 Using the template add city name, the country code, the weather description and maximum temperature for the city. 
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Max Temp</dt><dd>{Max Temp} °F</dd>
</dl>
"""

# 10a Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in itinerary_df.iterrows()]

# 10b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = itinerary_df[["Lat", "Lng"]]

In [14]:
# 11a. Add a marker layer for each city to the map.
max_temp = itinerary_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(marker_layer)

# 11b. Display the figure
fig

Figure(layout=FigureLayout(height='420px'))